db:
  image: postgres:latest
  ports:
    - "5432:5432"

web:
  build: .
  command: python manage.py runserver 0.0.0.0:5000
  ports:
    - "5000:5000"
  links:
    - db
  volumes:
    - .:/src
  environment:
    DEBUG: True
    SECRET_KEY: secretkey
    AWS_SECRET_ACCESS_KEY: aws_secret_access_key
    AWS_ACCESS_KEY_ID: aws_access_key_id
