db:
  image: postgres:latest
  ports:
    - "5432:5432"

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/src
  env_file: .env
